#!/bin/bash
node -e '
	const cp=require("child_process");

	function run(cmd,args){
		const output=cp.spawnSync(cmd,args,{encoding:"utf8"});
		const x1=output.stdout.trim();console.log(x1);
		return x1;
	}
	function update(){
		var lastCommitNumber=run("git",["log","-1","--pretty=%B"]);
		lastCommitNumber=parseInt(lastCommitNumber);
		if(isNaN(lastCommitNumber)){lastCommitNumber=0}
		lastCommitNumber=lastCommitNumber+1;
		lastCommitNumber=lastCommitNumber.toString();
		run("git",["add","."]);
		run("git",["commit","-m",lastCommitNumber]);
		run("git",["push","origin","master"]);		
	}
	
	module.exports.update=update;
	if(!module.parent){
		update()
	}
'
