#!/usr/bin/python
import subprocess
import json
from os import path
from collections import defaultdict
homeFolder = path.expanduser("~")
savePath = path.join( homeFolder , ".config" , ".xubuntu-keyboard-shortcuts.json" )

shortcuts = subprocess.check_output( [ "/usr/bin/xfconf-query -c xfce4-keyboard-shortcuts -l -v" ] , shell=True )

saveOBJ = defaultdict( lambda : None )
for index , rule in enumerate( shortcuts.splitlines() ):
	rule = rule.strip()
	rule = rule.split( " " )
	combo = rule[ 0 ]
	cmd = rule[ -1 ]
	if cmd == "<<UNSUPPORTED>>":
		continue
	saveOBJ[ index ] = { "combo": combo , "cmd": cmd }


print( "Saving to --> " + savePath )
with open( savePath , "w+" ) as outfile:
	json.dump( saveOBJ , outfile )