#!/usr/bin/python
import sys , os
import eyed3

path = os.getcwd()
if len( sys.argv ) > 1:
	path = sys.argv[ 1 ]

for ( dirpath , dirnames , filenames ) in os.walk( path ):
	for file in filenames:
		try:
			audio = eyed3.load( os.path.join( dirpath , file ) )
			print( audio.tag.title + " - " + audio.tag.artist )
		except:
			pass