#!/bin/bash
source ~/.nvm/nvm.sh
npm i -g npm
latestVersion=$(nvm ls-remote | grep 'Latest LTS' | tail -1 | awk '{print $1;}')
echo $latestVersion
nvm install $latestVersion
npm install pm2 -g
pm2 update
pm2 startup
