#!/usr/bin/python
import sys , os , random, string

wSAL = len( sys.argv )

w_length = 25
w_extra =  '!@#$%^*()'

cPOS = 0
if ( wSAL > 1 ):
	cPOS = wSAL - 1
	xT = sys.argv[ 1 ].isdigit()
	if ( xT == True ):
		w_length = int( sys.argv[ 1 ] )
		if ( ( cPOS + 1 ) < wSAL ):
			cPOS = cPOS + 1

	if ( sys.argv[ cPOS ] == "url" ):
		w_extra = "$-_.+!*'(),"
	elif ( sys.argv[ cPOS ] == "plain" ):
		w_extra = ""
	elif ( sys.argv[ cPOS ] == "numbers" ):
		w_extra = "numbersONLY"
				

if w_extra == "numbersONLY":
	chars = string.digits
else:
	chars = string.ascii_letters + string.digits + w_extra

def g_RAN_ITR():
	w_byte_seed = random.randrange( 1024 ,  2048 , 8 )
	random.seed = ( os.urandom( w_byte_seed ))
	x1 = ''.join( random.choice( chars ) for i in range( w_length ) )
	return x1

def b_RAN_ITR():
	wc = []
	for i in range( 0 , 10 ):
		x2 = g_RAN_ITR()
		wc.append( x2 )
	random.shuffle( wc )
	ws = []
	for s in range( 0 , 10 ):
		s1 = random.randint( 1 , w_length )
		s2 = random.randint( 1 , w_length )
		if ( s1 > s2 ):
			sT = s1
			s1 = s2
			s2 = sT
		sf = wc[ s ][ s1:s2 ]
		if len( sf ) > 1:
			ws.append( sf )
	random.shuffle( ws )
	ws = "".join( random.sample( ws , len( ws ) ) )
	xf = ws[ 0:w_length ]
	return xf

x1 = b_RAN_ITR()


if ( sys.argv[ cPOS ] == "lower"  ):
	x1 = x1.lower()
elif ( sys.argv[ cPOS ] == "upper" ):
	x1 = x1.upper()


print x1
