#!/usr/bin/python
import sys , os , random, string

wSAL = len(sys.argv)

w_length = 25
w_extra =  '!@#$%^*()'
if ( wSAL > 1 ):
	w_length = int(sys.argv[1])
if ( wSAL > 2 ):
	if ( sys.argv[2] == "url" ):
		w_extra = "$-_.+!*'(),"
	elif ( sys.argv[2] == "plain" ):
		w_extra = ""
	elif ( sys.argv[2] == "numbers" ):
		w_extra = "numbersONLY"

w_byte_seed = random.randrange( 1024 ,  2048 , 8 )

if w_extra == "numbersONLY":
	chars = string.digits
else:
	chars = string.ascii_letters + string.digits + w_extra

random.seed = ( os.urandom( w_byte_seed ))

x1 = ''.join(random.choice(chars) for i in range(w_length))


if ( wSAL ==  3 ):
	if ( sys.argv[2] == "lower"  ):
		x1 = x1.lower()
	elif ( sys.argv[2] == "upper" ):
		x1 = x1.upper()
if ( wSAL ==  4 ):
	if ( sys.argv[3] == "lower" ):
		x1 = x1.lower()
	elif ( sys.argv[3] == "upper" ):
		x1 = x1.upper()

print x1
