#!/usr/bin/python

import sys , os , time , subprocess

#https://github.com/shawnrice/alfred.flux

wTimeZones = [ 'America/Los_Angeles' , 'America/Denver' , 'America/Detroit' , 'Europe/London' ]
wBrazil = [ "-5.8" , "-35.2"  ]
wAustralia = [ "-33.8" , "151.2" ]
wSKorea = [ "37.5" , "127.0" ]
XFLUX_CMD_BASE = "xflux -k 2000"
XFLUX_CMD_NORMAL = XFLUX_CMD_BASE + " -z 98555"
XFLUX_CMD_FINAL = XFLUX_CMD_BASE

os.environ['TZ'] = wTimeZones[0]
time.tzset()
print time.strftime('%X %x %Z')

wExtra = ""
if ( len( sys.argv ) > 1 ): wExtra = sys.argv[1]

cHour = int( time.strftime( '%H' ) )
if ( wExtra  == "revert" ):
	XFLUX_CMD_FINAL = XFLUX_CMD_FINAL
else:
	if ( cHour == 24 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_NORMAL
	elif ( cHour == 23 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_NORMAL
	elif ( cHour == 22 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_NORMAL
	elif ( cHour == 21 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_NORMAL
	elif ( cHour == 20 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_NORMAL
	elif ( cHour == 19 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_NORMAL
	elif ( cHour == 18 ):	
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wBrazil[0] + " -g " + wBrazil[1]
	elif ( cHour == 17 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wBrazil[0] + " -g " + wBrazil[1]
	elif ( cHour == 16 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wBrazil[0] + " -g " + wBrazil[1]
	elif ( cHour == 15 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wBrazil[0] + " -g " + wBrazil[1]
	elif ( cHour == 14 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wBrazil[0] + " -g " + wBrazil[1]
	elif ( cHour == 13 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wBrazil[0] + " -g " + wBrazil[1]
	elif ( cHour == 12 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wBrazil[0] + " -g " + wBrazil[1]
	elif ( cHour == 11 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wBrazil[0] + " -g " + wBrazil[1]
	elif ( cHour == 10 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wBrazil[0] + " -g " + wBrazil[1]
	elif ( cHour == 9 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wBrazil[0] + " -g " + wBrazil[1]
	elif ( cHour == 8 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wBrazil[0] + " -g " + wBrazil[1]
	elif ( cHour == 7 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wBrazil[0] + " -g " + wBrazil[1]
	elif ( cHour == 6 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wSKorea[0] + " -g " + wSKorea[1]
	elif ( cHour == 5 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wSKorea[0] + " -g " + wSKorea[1]
	elif ( cHour == 4 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_FINAL + " -l " + wSKorea[0] + " -g " + wSKorea[1]
	elif ( cHour == 3 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_NORMAL
	elif ( cHour == 2 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_NORMAL
	elif ( cHour == 1 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_NORMAL
	elif ( cHour == 0 ):
		XFLUX_CMD_FINAL = XFLUX_CMD_NORMAL


print XFLUX_CMD_FINAL
subprocess.call( "sudo pkill xflux" , shell=True )
subprocess.call( XFLUX_CMD_FINAL , shell=True )
