#!/bin/bash
ssh -D $LOCAL_PORT -f -C -q -N -o IdentitiesOnly=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=60  -o LogLevel=ERROR  -F /dev/null \
-i /Users/$USERNAME/.ssh/$PRIVATE_KEY $USER@$REMOTE_VPS_IP
