#!/bin/bash

# sudo apt-get install x11proto-core-dev
# grep -l '#define.*XK_' /usr/include/X11/*.h

# xmodmap -pme
# xev -event keyboard | grep keycode
# xev | grep button
# xinput test 10 | grep "button press"
# xbindkeys -k

id=$(xinput | grep -m 1 "ELECOM TrackBall Mouse HUGE TrackBall" | sed 's/^.*id=\([0-9]*\)[ \t].*$/\1/')


#Button Constant Numbers
LEFT_CLICK=1
MIDDLE_CLICK=2
RIGHT_CLICK=3
WHEEL_UP=4
WHEEL_DOWN=5
WHEEL__LEFT=6
WHEEL_RIGHT=7
LEFT_ARROW=8
RIGHT_ARROW=9

# Custom Button Map
FN1=$LEFT_CLICK
FN2=$RIGHT_CLICK
L=$LEFT_CLICK
R=$RIGHT_CLICK
FN3=$RIGHT_CLICK
ARROW_UP=$LEFT_ARROW
ARROW_DOWN=$RIGHT_ARROW
SCROLL_WHEEL_CLICK=$MIDDLE_CLICK
SCROLL_WHEEL_UP=$WHEEL_UP
SCROLL_WHEEL_DOWN=$WHEEL_DOWN

#"Button Left" "Button Middle" "Button Right"
#"Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right"
# "Button Side" "Button Extra" "Button Forward" "Button Back" None

xinput --set-button-map $id $FN1 $SCROLL_WHEEL_CLICK $FN2 \
	$SCROLL_WHEEL_UP $SCROLL_WHEEL_DOWN 6 7 \
	$ARROW_UP $ARROW_DOWN $L $R $FN3


# nano ~/.xbindkeysrc

###########################
# xbindkeys configuration #
###########################
#keystate_numlock = enable
#keystate_capslock = enable
#keystate_scrolllock= enable

# Examples of commands:

#"xte 'key Page_Up'"
	#b:9

#"xte 'key Page_Down'"
	#b:8

##################################
# End of xbindkeys configuration #
##################################