#!/bin/bash

# sudo apt-get install x11proto-core-dev
# grep -l '#define.*XK_' /usr/include/X11/*.h

# xmodmap -pme
# xev -event keyboard | grep keycode
# xev | grep button
# xinput test 10 | grep button
# xbindkeys -k

id=$(xinput | grep -m 1 "ELECOM TrackBall Mouse HUGE TrackBall" | sed 's/^.*id=\([0-9]*\)[ \t].*$/\1/')

#Button Constant Numbers
LEFT_CLICK=1
MIDDLE_CLICK=2
RIGHT_CLICK=3
WHEEL_UP=4
WHEEL_DOWN=5
WHEEL__LEFT=6
WHEEL_RIGHT=7
LEFT_ARROW=8
RIGHT_ARROW=9

# Custom Button Map
FN1=$LEFT_CLICK
FN2=$RIGHT_CLICK
L=$LEFT_CLICK
R=$RIGHT_CLICK
FN3=$RIGHT_CLICK
ARROW_UP=$LEFT_ARROW
ARROW_DOWN=$RIGHT_ARROW
SCROLL_WHEEL_CLICK=$MIDDLE_CLICK
SCROLL_WHEEL_UP=$WHEEL_UP 
SCROLL_WHEEL_DOWN=$WHEEL_DOWN

xinput --set-button-map $id $FN1 $SCROLL_WHEEL_CLICK $FN2 $ARROW_DOWN $ARROW_UP 6 7 $SCROLL_WHEEL_DOWN $SCROLL_WHEEL_UP $L $R $FN3


# nano ~/.xbindkeysrc

###########################
# xbindkeys configuration #
###########################
#keystate_numlock = enable
#keystate_capslock = enable
#keystate_scrolllock= enable

# Examples of commands:

#"xte 'key Page_Up'"
	#b:4

#"xte 'key Page_Down'"
	#b:5

#"xdotool key Shift + Page_Down"
#"xdotool key Down Down Down"
	#b:8

#"xdotool key Shift + Page_Up"
#"xdotool key Up Up Up"
	#b:9

##################################
# End of xbindkeys configuration #
##################################
