#!/usr/bin/python
import sys
import datetime
format = "%H:%M:%S.%f"
endDate = datetime.datetime.strptime( sys.argv[2] , format )
startDate = datetime.datetime.strptime( sys.argv[1] , format )
diff = endDate - startDate
print diff
