#!/usr/bin/python

import sys
import os
import requests
import json

CLIENT_ID = ""

# https://dev.twitch.tv/docs/v5/reference/users/#get-user-by-id

def getUserInfo( username ):
	headers = {
		'Accept': 'application/vnd.twitchtv.v5+json' ,
		'Client-ID': CLIENT_ID ,
	}
	params = (
		( 'login' , username ) ,
	)
	response = requests.get( 'https://api.twitch.tv/kraken/users' , headers=headers , params=params )
	result = json.loads( response.text )
	return result

def getChannelInfo( user_id ):
	headers = {
		'Accept': 'application/vnd.twitchtv.v5+json' ,
		'Client-ID': CLIENT_ID ,
	}
	response = requests.get( 'https://api.twitch.tv/kraken/channels/' + str( user_id ) , headers=headers )
	result = json.loads( response.text )
	return result


if len( sys.argv ) < 2:
	sys.exit( 1 )

print( sys.argv[ 1 ] )
user = getUserInfo( sys.argv[ 1 ] )
print( user[ "users" ][ 0 ][ "_id" ] )
print( user[ "users" ][ 0 ][ "logo" ] )
channel = getChannelInfo( user[ "users" ][ 0 ][ "_id" ] )
print( channel[ "profile_banner" ] )
print( channel[ "video_banner" ] )

cmd1 = "/usr/bin/google-chrome '" + user[ "users" ][ 0 ][ "logo" ] + "'"
cmd2 = "/usr/bin/google-chrome '" + channel[ "profile_banner" ] + "'"
os.system( cmd1 )
os.system( cmd2 )
