#!/usr/bin/python
import sys , os , io
import distutils.dir_util
import json
import urllib

BASE_DIR = os.path.expanduser( "~" )
BASE_DIR = os.path.join( BASE_DIR , "TwitchEmotes" )
distutils.dir_util.mkpath( BASE_DIR )
IMAGES_JSON_FP = os.path.join( BASE_DIR , "images.json" )
IMAGES_JSON_URL = "https://twitchemotes.com/api_cache/v3/images.json"
#SETS_JSON_URL = "https://twitchemotes.com/api_cache/v3/sets.json"

EMOTE_ID = sys.argv[ 1 ]

def search_json():
	global EMOTE_ID
	json_data = open( IMAGES_JSON_FP )
	data = json.load( json_data )
	if EMOTE_ID in data:
		print data[ EMOTE_ID ]
		if data[ EMOTE_ID ][ "channel_name" ]:
			print "Channel Name == " + data[ EMOTE_ID ][ "channel_name" ]
		return True
	else:
		for emote_id in data:
			if data[ emote_id ][ "code" ] == EMOTE_ID:
				print data[ emote_id ]
				if data[ emote_id ][ "channel_name" ]:
					print "Channel Name == " + data[ emote_id ][ "channel_name" ]	
				return True
		return False

def re_download_and_search():
	print "Re-Downloading images.json"
	global IMAGES_JSON_URL
	global IMAGES_JSON_FP
	urllib.urlretrieve( IMAGES_JSON_URL , IMAGES_JSON_FP )
	if not search_json():
		print "Not in Twitch Database ???"

if os.path.isfile( IMAGES_JSON_FP ):
	if not search_json():
		re_download_and_search()
else:
	re_download_and_search()