#!/usr/bin/python
import sys
import os
import requests
import json

if len( sys.argv ) < 2:
	print( "something wadu" )
	sys.exit(1)

channel = sys.argv[1]
url = "http://tmi.twitch.tv/group/user/%s/chatters" % (channel)
headers = {

}
viewers = []
result = requests.get( url , headers=headers )
if not result.ok:
	print( "something wadu" )
	sys.exit(1)

result = result.json()
print( json.dumps( result , indent=4, sort_keys=True) )