#!/usr/bin/python
import sys , os , io
import distutils.dir_util
import json
import urllib
from pyquery import *

BASE_DIR = os.path.expanduser( "~" )
BASE_DIR = os.path.join( BASE_DIR , "TwitchEmotes" )
distutils.dir_util.mkpath( BASE_DIR )
IMAGES_JSON_FP = os.path.join( BASE_DIR , "images.json" )
IMAGES_JSON_URL = "https://twitchemotes.com/api_cache/v3/images.json"
#SETS_JSON_URL = "https://twitchemotes.com/api_cache/v3/sets.json"

EMOTE_ID = sys.argv[ 1 ]
try:
	float( EMOTE_ID )
except ValueError:
	URL = "https://twitchemotes.com/search?query=" + EMOTE_ID
	print URL
	html = PyQuery( url=URL )
	found_id = html( "a.emote-name" )
	if found_id is not None:
		found_id = found_id.attr( "href" )
		if found_id is not None:
			found_id = found_id.split( "/emotes/" )
			if found_id is not None:
				EMOTE_ID = found_id[ 1 ]

	if found_id is None:
		sys.exit(1)

print "Searching EMOTE-ID --> " + EMOTE_ID

def search_json():
	global EMOTE_ID
	json_data = open( IMAGES_JSON_FP )
	data = json.load( json_data )
	if EMOTE_ID in data:
		print data[ EMOTE_ID ]
		if data[ EMOTE_ID ][ "channel_name" ]:
			print "Channel Name == " + data[ EMOTE_ID ][ "channel_name" ]
		return True
	else:
		return False

if os.path.isfile( IMAGES_JSON_FP ):
	if not search_json():
		print "Re-Downloading images.json"
		urllib.urlretrieve( IMAGES_JSON_URL , IMAGES_JSON_FP )
		if not search_json():
			print "Not in Twitch Database ???"
else:
	print "Re-Downloading images.json"
	urllib.urlretrieve( IMAGES_JSON_URL , IMAGES_JSON_FP )
	if not search_json():
		print "Not in Twitch Database ???"
