#!/bin/bash
export DISPLAY=:0
#xdotool mousemove 2963 130
#xdotool click 1
#sleep .5
#twitchPlay
/usr/local/bin/replayMouseKeyboardActionFaster /home/morpheous/Documents/MouseRecords/Twitch/chat-close.data
