#!/usr/bin/python

# xfconf-query --create --channel xfce4-keyboard-shortcuts --property "/commands/custom/<Control><Alt>Down" --type string --set 'gedit'`
import subprocess
import json
from os import path
from collections import defaultdict
homeFolder = path.expanduser("~")
savePath = path.join( homeFolder , ".config" , ".xubuntu-keyboard-shortcuts.json" )

data = None
with open( savePath ) as f:
	data = json.loads( f.read() )


set_cmd_base = "xfconf-query --create --channel xfce4-keyboard-shortcuts --property '"
for key in data:
	cmd = set_cmd_base + data[ key ][ "combo" ] + "' --set '" + data[ key ][ "cmd" ] +"'"
	print cmd
	shortcuts = subprocess.check_output( [ cmd ] , shell=True )